# Generated by Django 4.2.4 on 2023-09-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='токен'),
        ),
    ]
