# Generated by Django 4.2.4 on 2023-09-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_blog_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='count_views',
            new_name='views_count',
        ),
    ]
