# Generated by Django 4.2.4 on 2023-09-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_name',
            field=models.TextField(max_length=200, verbose_name='Название версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.TextField(max_length=50, verbose_name='Номер версии'),
        ),
    ]
